#!/usr/bin/env sh
# generate all kind of symmetric pgp messages
for cipher_algo in IDEA 3DES CAST5 BLOWFISH AES AES192 AES256 TWOFISH CAMELLIA128 CAMELLIA192 CAMELLIA256; do
   gpg -c --passphrase a --s2k-mode 0 --cipher-algo ${cipher_algo} >${cipher_algo}-0.pgp </tmp/a
   for s2kmode in 1 3; do
      for s2k_cipher_algo in IDEA 3DES CAST5 BLOWFISH AES AES192 AES256 TWOFISH CAMELLIA128 CAMELLIA192 CAMELLIA256; do
         for s2k_digest_algo in MD5 SHA1 RIPEMD160 SHA256 SHA384 SHA512 SHA224; do
            echo ${cipher_algo}-${s2kmode}-${s2k_digest_algo}-${s2k_cipher_algo}.pgp
            gpg -c  --passphrase a --s2k-mode ${s2kmode} --s2k-digest-algo ${s2k_digest_algo} --s2k-cipher-algo ${s2k_cipher_algo} --cipher-algo ${cipher_algo} >${cipher_algo}-${s2kmode}-${s2k_digest_algo}-${s2k_cipher_algo}.pgp </tmp/a
         done
      done
   done
done
